export const ITEMS = [
  {
    id: 1,
    title: 'Page book',
    price: 10000,
    rating: 5,
    review: 84,
    imageUrl: '/assets/product-image-1.jpeg',
  },
  {
    id: 2,
    title: 'Monthly tracking sticker',
    price: 3000,
    rating: 5,
    review: 54,
    imageUrl: 'assets/product-image-2.jpeg',
  },
  {
    id: 3,
    title: 'Shape sticker',
    price: 4000,
    rating: 5,
    review: 22,
    imageUrl: 'assets/product-image-3.jpeg',
  },
  {
    id: 4,
    title: 'Index flag',
    price: 4500,
    rating: 5,
    review: 72,
    imageUrl: 'assets/product-image-4.jpeg',
  },
  {
    id: 5,
    title: 'Power sticker',
    price: 6000,
    rating: 4.9,
    review: 125,
    imageUrl: 'assets/product-image-5.jpeg',
  },
  {
    id: 6,
    title: 'Free memopad',
    price: 5500,
    rating: 4.9,
    review: 152,
    imageUrl: 'assets/product-image-6.jpeg',
  },
  {
    id: 7,
    title: 'Record memopad',
    price: 5000,
    rating: 5,
    review: 51,
    imageUrl: 'assets/product-image-7.jpeg',
  },
  {
    id: 8,
    title: 'Ad lib masking tape',
    price: 6000,
    rating: 5,
    review: 132,
    imageUrl: 'assets/product-image-8.jpeg',
  },
  {
    id: 9,
    title: 'Oval grid masking tape',
    price: 4000,
    rating: 5,
    review: 135,
    imageUrl: 'assets/product-image-9.jpeg',
  },
  {
    id: 10,
    title: 'Craft diary',
    price: 2000,
    rating: 4.9,
    review: 345,
    imageUrl: 'assets/product-image-10.jpeg',
  },
];
